- src/Checks/DatabaseHealthCheck.php
Without this, Lumen attempts to connect to a database with the
connection name of "default", rather than the connection named in
DB_CONNECTION .env variable
> Use empty string to connect to default database

- .github/workflows/run-tests.yml
- CHANGELOG.md
This is just a quick tweak to allow our tests workflow to run on PRs as well as pushes to master and the cron.
> Allow GitHub Actions to run on pull requests

- tests/Checks/CrossServiceHealthCheckTest.php
- tests/Checks/DatabaseHealthCheckTest.php
- tests/Controllers/HealthCheckControllerTest.php
- tests/Controllers/PingControllerTest.php
- tests/Facades/HealthCheckTest.php
- tests/HealthCheckServiceProviderTest.php
- tests/Middleware/AddHeadersTest.php
- tests/Middleware/BasicAuthTest.php
- tests/StatusTest.php
AssertSame reports an error if the two elements do not share type and value.
For example: this code $this->assertEquals(3, true); give uns true :-////
Please use assertSame, not assertEquals
> Change assertEquals to assertSame.

- tests/Checks/HttpHealthCheckTest.php
This adds tests to cover the cases where a `ConnectException` or general Exception is thrown.
It adjusts the test `shows_problem_if_connection_is_unreachable` to load the `http_error` middleware so a BadResponseException is properly thrown and handled.
This brings coverage of HttpHealthCheck to 100%
> Increase Test coverage for HttpHealthCheck

- tests/Checks/CacheHealthCheckTest.php
This adds a test to cover the case where the incorrect value is received from Cache and brings coverage of CacheHealthCheck to 100%
> Increase Test coverage for CacheHealthCheck

- src/HealthCheckServiceProvider.php
Right now, `base_bath` configuration was never used when registering routes.
> Use base_bath configuration

- CHANGELOG.md
- src/HealthCheckServiceProvider.php
After tagging `v1.9.0` we've found a bug which prevents `/health` from working due to `Router::name()` being undefined.
I've fixed it in this MR and tested in Laravel 5.4 and Lumen 7.
> Fix Lumen named route bug

- composer.json
- src/Commands/HealthCheckMakeCommand.php
- src/Commands/Stubs/ExampleHealthCheck.php.stub
- src/HealthCheckServiceProvider.php
- tests/Commands/HealthCheckMakeCommandTest.php
- tests/HealthCheckServiceProviderTest.php
I accidentally force pushed to #30 and broke the diff so I've duplicated the code here.
I'll sort out the tests because I know the previous MR was having trouble so we can get this merged this week.
> Add health check make command

- config/healthcheck.php
- src/HealthCheckServiceProvider.php
- tests/Controllers/HealthCheckControllerTest.php
- tests/Controllers/PingControllerTest.php
In my use case, we would like to use the`/healthz` path commonly used in the Kubernetes and Docker ecosystem. This change should allow us to override this path without affecting existing default functionality for the non-z paths.
> Allow overriding health and ping route paths

- src/HealthCheckServiceProvider.php
- tests/Controllers/HealthCheckControllerTest.php
A backwards incompatible change was spotted which defaulted the `/ping` & `/health` routes for existing uses of the package using existing config to both listen on `/`.
This adds a fallback so if the config doesn't exist it defaults to  `/ping` & `/health`.
Alongside this, I've added a test for the `/ping` customization and tweaked the `/health` customisation test as this still had the default `/health` route due to how orchestra bootstraps Laravel.
> Fix Backwards Incompatible Config Additions

- config/healthcheck.php
- src/Checks/EnvHealthCheck.php
- tests/Checks/EnvHealthCheckTest.php
`UKFast\HealthCheck\Checks\EnvHealthCheck` creates false positives when an environment value is _set_ but its value is `null`.
This happens because `if (env($env) === null)` returns `true` for `null` values, as `env('MISSING_KEY')` returns `null`.  
Passing a (configurable) default value to `env()` makes it easy to check if the default value was returned (which is what we really want).
> fix(check): env check false positive when value is defined but null

- composer.json
I would be the first to admit I am not an advanced user of this package, but after some basic testing this package appears to be working as expected with the ^9.0 range.
Thank you!
> Adds 9.0 to illuminate/* dependencies

- src/Checks/StorageHealthCheck.php
php uniqid does not guarantee uniq ids in storage healthcheck.. that produces in my project failing checks.. the problem is about concurrency.. when the infrastructure is fast enough you can create same uniqid for diferent checks in the same microsec.. causing the misinformation
https://www.php.net/manual/en/function.uniqid.php#120123
> adding more entropy to the uniqid in the storagehealthcheck

- composer.json
- src/Status.php
https://phpunit.de/announcements/phpunit-10.html
There's a bigger piece of work around supporting PHPUnit 10 so for now I think it's fine for us to stay on v9.
We should probably look at what PHP versions we want to support moving forwards and set up our testing dependency versions based on that.
> Stop PHPUnit 10 being installed till we can fix deprecation errors in v9

- config/healthcheck.php
- src/Controllers/HealthCheckController.php
This gives much more flexibility to manage the response http code. For example, the most clear way for me to respond with 417 code, as app actually runs well. It does not care of 3xx, 4xx, 5xx.... on any onther endpoint I made check up. But if package or app fails then that the moment for me where 500 may take place. Anyway, it is left default as 500, so, nothing affected negatively.
> Config. default-problem-http-code for Controller

- README.md
- src/Commands/StatusCommand.php
- src/Controllers/HealthCheckController.php
- src/HealthCheckServiceProvider.php
- tests/Commands/StatusCommandTest.php
- tests/Controllers/HealthCheckControllerTest.php
Because [#44](https://github.com/ans-group/laravel-health-check/pull/44) hasn't been updated for a long time...
So I have reference to  [#44](https://github.com/ans-group/laravel-health-check/pull/44) to fix the conflict and some modifications
Hope this feature can be updated
> (#22) Add health-check:health command

- .github/workflows/run-tests.yml
- CHANGELOG.md
- composer.json
- config/healthcheck.php
- src/Checks/PackageSecurityHealthCheck.php
- tests/Checks/PackageSecurityHealthCheckTest.php
- tests/json/securityCheckerPackageHasVulnerability.json
Resolves #63.
Moving from sensiolab to enlightn because sensiolab is abandoned.
Original PR:
https://github.com/ans-group/laravel-health-check/pull/64
> Fix package security check

- composer.json
- src/Checks/FtpHealthCheck.php
- src/HealthCheck.php
- tests/Checks/FtpHealthCheckTest.php
Laravel 11 specifies v3 of flysystem and the current implementation of this was for v1. v2 saw a refactor that has affected this check, so we need to update this.
> Fix ftp check

- .phpmd/ruleset.xml
- src/Checks/DatabaseHealthCheck.php
- src/Checks/HttpHealthCheck.php
- tests/Checks/CacheHealthCheckTest.php
- tests/Checks/DatabaseHealthCheckTest.php
- tests/Checks/EnvHealthCheckTest.php
- tests/Checks/HttpHealthCheckTest.php
- tests/Checks/LogHealthCheckTest.php
- tests/Checks/MigrationUpToDateHealthCheckTest.php
- tests/Checks/PackageSecurityHealthCheckTest.php
- tests/Checks/RedisHealthCheckTest.php
- tests/Checks/SchedulerHealthCheckTest.php
- tests/Checks/StorageHealthCheckTest.php
- tests/Commands/HealthCheckMakeCommandTest.php
- tests/Controllers/HealthCheckControllerTest.php
- tests/Controllers/PingControllerTest.php
- tests/Stubs/Log/BadLogger.php
- tests/Stubs/Log/NullLogger.php
- tests/Stubs/Redis/Connections/PhpRedisClusterConnection.php
Adds the following rules:
- Controversial
- Naming
- Unused code
#86
> Add more PHPMD Rules

- composer.json
- phpstan.neon.dist
- src/HealthCheckServiceProvider.php
- tests/Checks/CacheHealthCheckTest.php
- tests/Checks/FtpHealthCheckTest.php
- tests/Checks/SchedulerHealthCheckTest.php
- tests/Checks/StorageHealthCheckTest.php
Adds Larastan and brings the code inline with level 0.
Level 0:
> These checks basic checks, unknown classes, unknown functions, unknown
methods called on $this, wrong number of arguments passed to those
methods and functions, always undefined variables
#86
> Add larastan

- .phpmd/ruleset.xml
- phpstan.neon.dist
- src/Checks/MigrationUpToDateHealthCheck.php
- tests/Checks/RedisHealthCheckTest.php
- tests/HealthCheckServiceProviderTest.php
This is the next Larastan bump.
Level 4:
Basic dead code checking - always false instanceof and other type checks, dead else branches, unreachable code after return; etc.
> Bump Larastan to level 4

- phpstan.neon.dist
- src/AppHealth.php
- src/Checks/HttpHealthCheck.php
- src/Checks/PackageSecurityHealthCheck.php
- tests/Checks/CrossServiceHealthCheckTest.php
- tests/Checks/FtpHealthCheckTest.php
This is the next Larastan bump.
Level 5:
Checking types of arguments passed to methods and functions
#86
> Bump Larastan to level 5

- composer.json
- phpstan.neon.dist
In trying to upgrade to Laravel 12 I was hit with some problems because of the dependency requirements in this package.  I went through and updated dependencies so that it would be possible to upgrade Laravel and keep using this package.  Larastan started throwing more errors, so I updated the baseline since there were no code changes.  The list of errors I saw before/after the upgrade are:
Pre upgrade errors:
```
------ ------------------------------------------------------------------------------------------------------------------------------------------- 
Line   src/Checks/FtpHealthCheck.php                                                                                                              
------ -------------------------------------------------------------------------------- …
```
> Update Dependencies & Larastan Baseline

- composer.json
- src/Checks/PackageSecurityHealthCheck.php
Same Laravel 12 support changes from the PR by @laravel-shift, but includes PHPStan fixes for the error in PackageSecurityHealthCheck
> Laravel 12 Support
